# Generated by Django 2.1.4 on 2018-12-06 19:07

from django.db import migrations, models
import django.utils.timezone
import lostandfoundapp.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_or_found', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('slug', models.SlugField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('contact_person_name', models.CharField(max_length=20)),
                ('contact_person_mobile_or_email', models.CharField(max_length=30, validators=[lostandfoundapp.validations.validate_person_email_or_contact])),
                ('date_found_or_lost', models.DateField(default=django.utils.timezone.now)),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('date_solved', models.DateField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('author_email', models.CharField(blank=True, max_length=50, null=True)),
                ('claimer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('claimer_identity_type', models.CharField(blank=True, max_length=30, null=True)),
                ('claimer_identity_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
