# Generated by Django 2.1.4 on 2018-12-06 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='date_found_or_lost',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='lost or found date '),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='lost_or_found',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='title',
            field=models.CharField(help_text='e.g Lost mobile at 210 lab.', max_length=50),
        ),
    ]
